site_name: Python with Notebooks


nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Shapes: n2shapes.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition


theme:
  name: "material"  # Add this line to specify the theme

  features:
    - content.code.copy



