site_name: Blender with Notebooks


nav:
  - Home: index.md
  - Getting Started: n1getting_started.md
  - Settings: n2settings.md




extra_css:
  - style.css


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition


plugins:
    - mkdocs-jupyter


theme:
  name: "material"  # Add this line to specify the theme

  features:
    - content.code.copy


